name: Deploy Application

# イベントトリガーの設定
on:
  push: # pushイベントがトリガー
    branches:
      - main
  pull_request: # プルリクエストイベントがトリガー
    branches:
      - main

# ジョブの定義
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   steps:

     # デプロイする
     - name: Deploy
       run: |
         # SSH接続して、git pullする
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
         chmod 600 private_key
         ssh -oStrictHostKeyChecking=no ${{ secrets.AWS_USER_NAME }}@${{ secrets.AWS_PUBLIC_IPV4_DNS }} -i private_key "
           cd ~/text-snippest && \
           git fetch https://github.com/sunny-side-app/text-snippest.git && \
           git pull https://github.com/sunny-side-app/text-snippest.git && \
           echo 'DATABASE_NAME=${{ secrets.DATABASE_NAME }}' > .env && \
           echo 'DATABASE_USER=${{ secrets.DATABASE_USER }}' >> .env && \
           echo 'DATABASE_USER_PASSWORD=${{ secrets.DATABASE_USER_PASSWORD }}' >> .env
         "

